### ISSUE TITLE
Restarting Safari requires uBlock purge & update or pages/filters break every time 

### ISSUE THREAD

**Issue by BillyJoeJimBob** [el1t/uBlock-Safari#26] opened 2017-02-10 11:18 UTC
### Describe the issue
Every time I restart Safari, many elements are hidden on some websites until I go to the "3rd Party Filters" tab and hit the "Purge All Caches" button followed by the "Update" button.  This happens whether my mac has been running all day or after a cold restart.  Simply refreshing the page has no effect.  

It also appears that some, but not all, of uBlock's filters remain operative even after deselecting individual 3rd party and custom "My Filters" on the 3rd Party Filters Tab and the "I Am An Advanced User" button in the "Settings Tab"; then restarting Safari.  All of this happens even if I uncheck every option and filter box in the Settings and 3rd-Partys tabs.  

This is not desirable because I can't control which elements are or aren't hidden.

All other extensions are disabled, Safari is on either default or less restrictive settings.   

None of this occurs when using the current version of uBlock Origin in Chrome or Firefox.  Disabling uBlock Origin in Safari returns to the expected behavior: no filtering at all.

This may be related to issue # 13 on cosmetic filtering, which you addressed previously.  My best guess is a cache issue, but I don't really know.

### One or more specific URLs where the issue occurs
http://www.cnn.com
http://money.cnn.com
https://www.bing.com
http://www.bing.com
http://www.pcmag.com
  
### Screenshot in which the issue can be seen 

in each example below, part a is after Safari has been restarted with all filters unchecked. 

1a:  uBlock dashboard after unchecking all filters and restarting Safari, note the number of network and cosmetic filters listed is as over 100,000 even though all filters are unchecked:

![ublock dashboard before purge update](https://cloud.githubusercontent.com/assets/11702508/22823907/a35c86da-ef3a-11e6-9b41-b89b2ba9a201.png)

1b: uBlock dashboard above after further clicking Purge, then Update:

![ublock dashboard after purge update](https://cloud.githubusercontent.com/assets/11702508/22823970/e0a87828-ef3a-11e6-94bf-71a04b1a74cd.png)

2a:  bing.com before purge & update (entire background is black/blank):

![bing before purge update](https://cloud.githubusercontent.com/assets/11702508/22824068/3c7edf48-ef3b-11e6-8e64-6a5e6586024b.png)

2b.: bing .com after purge & update:

![bing after purge update](https://cloud.githubusercontent.com/assets/11702508/22824094/503cabd2-ef3b-11e6-8904-feeefd87dae9.png)

3a.:  cnn.com before purge & update:

![cnn - before purge update](https://cloud.githubusercontent.com/assets/11702508/22824189/a6a34d0a-ef3b-11e6-92ec-56ac88ce38a2.png)

3b.:  cnn.com after purge & update:

![cnn - after purge update](https://cloud.githubusercontent.com/assets/11702508/22824223/d1c7e720-ef3b-11e6-92fb-b9c025151bf7.png)

4a.:  money.cnn.com before purge & update:

![cnnmoney - before purge update](https://cloud.githubusercontent.com/assets/11702508/22824274/10259c60-ef3c-11e6-86f2-772b1905412e.png)

4b.:  money.cnn.com after purge & update:

![cnnmoney - afterpurge update 1](https://cloud.githubusercontent.com/assets/11702508/22824348/66c53620-ef3c-11e6-86d9-77863057ea22.png)
![cnnmoney - afterpurge update2](https://cloud.githubusercontent.com/assets/11702508/22824384/8e442df0-ef3c-11e6-8251-8fcd7a9bc035.png)
![cnnmoney - afterpurge update3](https://cloud.githubusercontent.com/assets/11702508/22824397/9ddc41da-ef3c-11e6-9cc2-85ce88b49d85.png)
![cnnmoney - afterpurge update4](https://cloud.githubusercontent.com/assets/11702508/22824406/a95b0d02-ef3c-11e6-99df-6b3342ce8bbf.png)

5a.:  pcmag.com, before purge & update:

![pcmag before purge update](https://cloud.githubusercontent.com/assets/11702508/22824628/8ade679c-ef3d-11e6-8b76-ac0d441d74a0.png)

5b.:  pcmag after purge & update:

![pcmag after purge update](https://cloud.githubusercontent.com/assets/11702508/22824681/c1051032-ef3d-11e6-8325-cd966d477c7f.png)

### Steps for anyone to reproduce the issue
1. Restart Safari.
2. Go to one of these web sites: money.cnn.com; cnn.com; bing.com; pcmag.com
3. View the web page, in my case, page elements that should be visible are missing, other elements are visible that should be blocked by uBlock filters.
4. Go to the 3rd Party filters tab, first click the Purge button, then hit the Update button in uBlock settings, wait for the update to complete.
5. View the web page(s) after the purge & update.  In my case, they are now functioning as expected.

--Alternative--
Before restarting Safari in step 1, above, uncheck all the filter boxes in the 3rd-party filters tab including the my filters box, and uncheck the advanced user box in the settings tab.  In my case, the page acts as though many of the filters are still enabled.

### Your settings

- Safari version: 10.0.3
- uBlock Origin version: 1.11.1.0
- MacOS version: 10.12.3

##### Your filter lists

1: "Default filter lists + Anti-Adblock Killer + Fanboy's Enhanced Tracking List", or 
2: all filters disabled

#####  Custom filters:

cnn.com#@#.OUTBRAIN
cnn.com##.AR_33.ob_strip_container
cnn.com##.cnn-politics-tos--visible.cnn-politics-tos
cnn.com##.CRAB_1.ob-strip-layout.ob-widget
cnn.com##.CRAB_3.ob-strip-layout.ob-widget
cnn.com##.CRAB_4.ob-one-column-layout.ob-widget
cnn.com##.ob_dual_left
cnn.com##.ob-hover.ob_what
cnn.com###health-zone-8
cnn.com###homepage3-zone-1 > * > * > .zn__column--idx-2.column
cnn.com###living-zone-8
cnn.com###politics-zone-6
cnn.com###travel-zone-8
cnn.com###us-zone-7
cnn.com###world-zone-6

Thank you for your work on this project.

**Comment by gorhill** [comment] 2017-02-10 13:09
1a: did you click _"Apply changes"_ after un-checking all filter lists?

1b: can you provide a screenshot of the whole _"3rd-party filters"_ pane? _"57 network filters ＋ 802 cosmetic filters from"_ matches **exactly** what one would have with the filter list _"EU: Prebake - Filter Obtrusive Cookie Notices"_.

**Comment by BillyJoeJimBob** [comment] 2017-02-10 19:48
Thank you for the quick reply.  You are correct, I had the EU: Prebake list checked.  I retraced my steps and have new, more complete screen shots below.

First, I opened Safari, opened the 3rd Party filters tab and deselected all filters, including "My Filters", leaving only "Auto-update filter lists" and "Parse and enforce cosmetic filters" as the only checked options.  Then I clicked Apply changes.  I then opened the Settings tab and deselected the "I am an advanced user" option.  Next I closed and quit Safari.  I then restarted Safari and took screen shots 1a-5a below.  The 3rd party filters tab shows 100,000+ filters active at this point and websites respond as if some of the filters are enabled.

After taking screens shots 1a-5a, I returned to the 3rd Party filters tab, which was still showing 100,000+ filters active and the "Update Now" and "Purge all caches" were greyed out. I selected one of the filter boxes which caused the "Apply changes" button to appear.  I clicked the "Apply changes" and the number of active filters changed.  I deselected that same filter followed by the "Apply changes" button again, now the number of active filters is 0 and webpages .  I then took screen shots 1b-5b below.  At this point, if I close, quit and restart Safari, the 3rd Party filters tab will revert to showing 100,000+ filters active, even though all of the filters remain unchecked.  It will again treat web pages as though many filters are enabled until I repeat the above steps.

1a.  uBlock Origin dashboard after unchecking all filters, closing and quitting Safari, then restarting:

![image](https://cloud.githubusercontent.com/assets/11702508/22841169/6a2bf53a-ef85-11e6-8f70-3967dbcdcf88.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22841199/7ffc1dcc-ef85-11e6-9c02-5ac845938162.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22841252/ae8b6594-ef85-11e6-912c-db768f6dd9ac.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22841279/ca0b77b4-ef85-11e6-8808-764ad0f2ffe9.png)

1b.  uBlock Origin dashboard after checking a filter, clicking apply changes, deselecting that filter, the clicking apply changes again:

![image](https://cloud.githubusercontent.com/assets/11702508/22841418/61647444-ef86-11e6-9e31-f0cd8d250db6.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22841432/78d3bd56-ef86-11e6-8137-c970e377edd8.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22841445/84210aba-ef86-11e6-8fef-86a8f89d178b.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22841465/95448736-ef86-11e6-97f3-eeda933aff63.png)

Screenshots of example websites 2a/2b - 5a/5b will follow in a subsequent post.

**Comment by gorhill** [comment] 2017-02-10 20:09
You don't need to show all filter lists, my original demand was because your 3rd-party filters pane was saying "57 network filters ＋ 802 cosmetic filters from" which you confirmed because EU Cookies was still selected.

**Comment by gorhill** [comment] 2017-02-10 20:19
> First, I opened Safari, opened the 3rd Party filters tab and deselected all filters, including "My Filters", leaving only "Auto-update filter lists" and "Parse and enforce cosmetic filters" as the only checked options. Then I clicked Apply changes.

When you un-select all filters (before 1a) then click _"Apply change"_ and before quitting Safari, do the filter counts change to zero in the 3rd-party filters pane?

**Comment by BillyJoeJimBob** [comment] 2017-02-10 20:23
Screenshot 2a, showing bing.com after filters deselected and Safari restarted, but before "Apply changes" button clicked:

![bing 2017-02-10 10-13-08](https://cloud.githubusercontent.com/assets/11702508/22841781/ac36aef0-ef87-11e6-9625-d3d95ad269ae.png)

Screenshot 2b, bing.com after "Apply changes" button clicked:

![bing 2017-02-10 10-20-10](https://cloud.githubusercontent.com/assets/11702508/22841804/cd425892-ef87-11e6-804b-f3a592997928.png)

Screenshot 3a, cnn.com before:

![cnn - breaking news latest news and videos 2017-02-10 10-13-43](https://cloud.githubusercontent.com/assets/11702508/22841953/5fa32540-ef88-11e6-9987-7844a4e3d3a9.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22841965/6cd22752-ef88-11e6-9e43-b18f03ad6a5d.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22841975/73c38da8-ef88-11e6-9804-3ad5219cf969.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22841980/7b9837cc-ef88-11e6-8807-db92a4338c94.png)

Screenshot 3b, cnn.com after:

![image](https://cloud.githubusercontent.com/assets/11702508/22842187/33a58efa-ef89-11e6-95ab-7046eed12dcc.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842197/3b17ee12-ef89-11e6-8d9d-1697c60e6487.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842201/42a519e8-ef89-11e6-94a7-dddec5a41eae.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842207/48a259c8-ef89-11e6-9219-c5048bc63902.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842217/52ce95e2-ef89-11e6-84f2-549eaefaea56.png)

Screenshot 4a, money.cnn.com before:

![image](https://cloud.githubusercontent.com/assets/11702508/22842303/a16a556a-ef89-11e6-8168-07bbedf67fb2.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842312/aa506aca-ef89-11e6-90cd-1deb61860c13.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842321/b201ddd0-ef89-11e6-9fba-f2f43290b882.png)

Screenshot 4b, money.cnn.com after:

![image](https://cloud.githubusercontent.com/assets/11702508/22842452/23fac1ae-ef8a-11e6-8419-e62fc2f0a8ef.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842475/312a5a9c-ef8a-11e6-8e50-b4ed21b042b9.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842500/4309fc72-ef8a-11e6-8283-40e8ed15ab0e.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842520/54535b7c-ef8a-11e6-853d-4266eb6a247a.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842533/5d0d6da2-ef8a-11e6-931c-2c691da3424c.png)

Screenshot 5a, pcmag.com before:  

![image](https://cloud.githubusercontent.com/assets/11702508/22842621/bdf509cc-ef8a-11e6-9264-f76d978250d1.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842626/c45a00e2-ef8a-11e6-956e-60aa37b56d09.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842633/cb73aaea-ef8a-11e6-956e-63314f1176ef.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842643/d1eeb036-ef8a-11e6-889b-52e967418719.png)

Screenshot 5b, pcmag.com after:

![image](https://cloud.githubusercontent.com/assets/11702508/22842784/668c2818-ef8b-11e6-86c7-b54d5a81ec90.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842788/6e50d8e6-ef8b-11e6-82c5-89f5681b6689.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842815/81e1f85e-ef8b-11e6-8993-e045329bff80.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842825/8957d662-ef8b-11e6-9f55-95bfea1113da.png)
![image](https://cloud.githubusercontent.com/assets/11702508/22842835/8ef9d5ac-ef8b-11e6-83d0-826a1be1c5a1.png)

-- Again, thank you for you assistance.

**Comment by BillyJoeJimBob** [comment] 2017-02-10 20:37
When I un-select all filters at 1a, then click "Apply change" and before quitting Safari, the filter counts do indeed  change to zero in the 3rd-party filters plane.  When I subsequently close, then quit, then restart Safari, the 3rd-party filters pane reverts to showing 100,000+ filters enabled while at the same time, all of the individual filter boxes remain unchecked.

**Comment by gorhill** [comment] 2017-02-10 20:57
> When I subsequently close, then quit, then restart Safari, the 3rd-party filters pane reverts to showing 100,000+

@el1t From the look of it, it is as if the selfie is not removed from the cache storage. This is were the call is made: <https://github.com/gorhill/uBlock/blob/cbca48307c50d4e243462c4c86af03453bbdf766/src/js/storage.js#L919>.

When the user clicks _Apply changes_, the line above should be executed. Given that there is [no callback passed to `localForage.removeItem`](https://github.com/el1t/uBlock-Safari/blob/0240a408dbb980434c55285cd84f2569ed07055e/platform/safari/vapi-background.js#L204), I wonder if it's possible that the operation never actually completes in the current scenario, though that would be quite surprising given the delay between clicking _Apply changes_ and quitting the browser.

**Comment by BillyJoeJimBob** [comment] 2017-02-10 22:56
Do you think this issue is universal or is it just my machine?

**Comment by el1t** [comment] 2017-02-13 06:46
Sorry for the delay. I can't seem to trigger this behavior; here's what I've tried:
1. Check only default filters, click apply
1. Uncheck all filters, click apply
(number active changes to 0+0)
1. Visit website (money.cnn.com, no filters visible)
1. Restart Safari
1. Check 3rd party filters, shows 0+0 enabled
1. Visit website (same, no filters visible)

Let me know if I missed something there. I tried closing Safari quickly after applying changes, but the changes still commit. Also, I verified that `selfie` is undefined after hitting apply.

**Comment by BillyJoeJimBob** [comment] 2017-02-13 14:13
Following your steps, if at step 4 I just close Safari via the red button and then reopen, I get the behavior you described.  If I quit Safari from the drop menu and then reopen, I get the following results:  

Screenshot 1, uBlock Origin with default filters checked:

![ublock dashboard 2017-02-13 05-45-33](https://cloud.githubusercontent.com/assets/11702508/22886202/b5468d40-f1b1-11e6-9954-6a4e8367aabe.png)
 

Screenshot 2, uBlock Origin with no filters checked and the number of filters enabled reads as zero:

![ublock dashboard 2017-02-13 05-46-17](https://cloud.githubusercontent.com/assets/11702508/22886640/964f4538-f1b3-11e6-8b60-d2ec87705850.png)


Screenshot 3, uBlock Origin after quitting Safari and then reopening now showing a large number of filters enabled (larger number than in screenshot 1):

![ublock dashboard 2017-02-13 05-47-04](https://cloud.githubusercontent.com/assets/11702508/22886469/e0ca568a-f1b2-11e6-826f-c9a0271107da.png)

The advanced user option for dynamic filters is disabled, all other add-ons disabled.  I will try and replicate this on a different Mac today.

**Comment by BillyJoeJimBob** [comment] 2017-02-13 14:20
After step 3 above, if I check any one of the 3rd party filters and then apply, the number of filters indicated changes to just that of the newly checked filter.  Further unchecking that filter again results in the total number returning to zero.

**Comment by BillyJoeJimBob** [comment] 2017-02-13 23:40
I tried this again on another Mac and there were no issues.  I uninstalled and trashed uBlock Origin on the problematic Mac and downloaded it again and the issue is no longer present, so it was likely unique to this Mac.  The only remaining quirk is the bing.com  background is still black when using EasyPrivacy filter, which doesn't occur in Chrome or Firefox.  Thank you for your assistance.

**Closed as completed** 2017-03-21 05:44 UTC
