### ISSUE TITLE
Element picker tools don't work 

### ISSUE THREAD

**Issue by ghost** [el1t/uBlock-Safari#92] opened 2018-01-25 18:45 UTC
> Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
The element picker tools do not work. If I click on them nothing happens.

### One or more specific URLs where the issue occurs

> [URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

> [Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. OPen Safari and browse to a random page
2. Use the element picker tools - nothing happens
3. This issue does not occur in Chrome with the same version of uBlock origin
### Your settings

> [If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- MacOS version: 10.13.3
- Safari version: 11.0.3
- uBlock Origin version: 1.14.24

##### Your filter lists

> [Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment] 2018-01-25 18:46
Duplicate of #88.

**Closed as completed** 2018-01-25 18:47 UTC
