### ISSUE TITLE
Safari can’t install this extension

### ISSUE THREAD

**Issue by david-macrae** [el1t/uBlock-Safari#86] opened 2018-01-19 00:00 UTC
> Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

the latest build 1.14.24 that was just uploaded will not install.

safari just pops up with a warning: Safari can’t install this extension
### One or more specific URLs where the issue occurs

> [URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

> [Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

> [If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- MacOS version: 
- Safari version: 
- uBlock Origin version: 

##### Your filter lists

> [Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by ghost** [comment] 2018-01-19 00:01
Yeah same here, and the update button in Safari Extension Updates does nothing.

**Comment by Baccount** [comment] 2018-01-19 00:18
Im also effected running macOS 10.13.2 (17C205) Safari 11.0.2

**Comment by danmcquade** [comment] 2018-01-19 00:20
Same issue here. Tried on two different Macs, both running 10.13.2 (17C205) with Safari 11.0.2.

![screen shot 2018-01-18 at 7 20 01 pm](https://user-images.githubusercontent.com/1420706/35128454-99d92eee-fc84-11e7-9f8c-91eaea095e5a.png)

**Comment by mustii82** [comment] 2018-01-19 02:37
same problem :/

**Comment by ruchernchong** [comment] 2018-01-19 03:12
macOS Version: macOS 10.13.3 Beta 4 (17D39a)
Safari Version: Version 11.0.3 (13604.5.6)

## Description:
Unable to install the extension for `1.14.24`

**Comment by sheelgautam** [comment] 2018-01-19 04:33
macOS Version 10.13.2 (17C205)
Safari Version 11.0.2 (13604.4.7.1.6)

Can install Ub0 1.14.14 but cannot install 1.14.24.
Error : Safari can't install this extension.
Can install other extensions in addition to extensions from Safari Extension Gallery.

**Comment by MysticalOS** [comment] 2018-01-19 08:32
Won't install or upgrade from gallery in safari or tech preview. it just rejects .24 version

**Comment by maciboy** [comment] 2018-01-19 09:35
Same :/

**Comment by volcbs** [comment] 2018-01-19 14:14
Wow, I thought I was the only one. Got the same problem here.
MacOS 10.12.6
Safari 11.0.2

**Comment by gorhill** [comment] 2018-01-19 14:20
Did any of you try what was suggested in <https://github.com/el1t/uBlock-Safari/issues/85#issuecomment-357420212>?

> Run `sudo softwareupdate -i -a` in terminal and it should install any updates.

**Comment by danmcquade** [comment] 2018-01-19 14:23
> Did any of you try what was suggested in #85 (comment)?

Tried this on both of my machines. Both are fully up to date and 1.14.24 still fails to install.

**Comment by manuseoane** [comment] 2018-01-19 16:03
Same here on Safari 11.0.2, macOS 10.11.6.

Maybe an issue related to Safari >= 11.0.2?

**Comment by maciboy** [comment] 2018-01-19 16:14
@gorhill 
No updates are available for my system

**Comment by vassudanagunta** [comment] 2018-01-19 16:28
@MysticalOS @sheelgautam The unauthorized build [has been reported to have finally been removed from the extensions gallery](https://github.com/el1t/uBlock-Safari/issues/69#issuecomment-357223225).  Are you still finding it there?

**Comment by sheelgautam** [comment] 2018-01-19 16:55
@vassudanagunta 
Nope.
I meant that I could install other extensions from the Extensions Gallery. Ublock Origin is not on it. My earlier comment probably caused confusion.

**Comment by fostermarke** [comment] 2018-01-19 17:14
Extension won't install here either. Clicking update in the prefpane does nothing and downloading to install manually produces the error dialog show earlier. This is Safari 11.0.2 on both 10.13.2 and 10.11.6.

**Comment by dnblankedelman** [comment] 2018-01-19 17:20
I have yet to try and reproduce this, but I am curious (in an attempt to help the developers who I really appreciate): when this fails, any messages at all in the OSX console, Safari web inspector/console, some other log source? Any useful info from Xcode or the Extension builder in the Develop menu (have to turn it on in preferences)? 

Just wondering if Safari logs any more useful info any place else beyond a "it be broke" dialogue.

**Comment by mamedker** [comment] 2018-01-19 17:27
Same there but nevertheless, thanks for the great work !

Hope it'll be fixed soon

**Comment by sidneys** [comment] 2018-01-19 17:29
same here, neither update nor fresh install works.

**Comment by iAYMANi** [comment] 2018-01-19 17:30
Same issue here

**Comment by timbuktu234** [comment] 2018-01-19 18:52
Exactly same problem as original poster. Extension fails to install. 

*Running macOS 10.13.2 (17C205)* 
*Safari Version 11.0.2 (13604.4.7.1.6)*
*on MacBook Pro Mid 2014*

<img width="532" alt="screen shot 2018-01-19 at 10 52 23 am" src="https://user-images.githubusercontent.com/460897/35166460-dc421854-fd06-11e7-8d69-3c08f9acbcd9.png">

**Comment by CalbertAmu** [comment] 2018-01-19 19:28
Same issue here

_Running macOS 10.12.4
Safari Version 10.1
Mac Air Early 2015_

**Comment by SLGiHub** [comment] 2018-01-20 07:37
Yeah same here after following manual install instructions, fails to install

**Comment by marcothuemmler** [comment] 2018-01-20 08:33
`./tools/make-safari.sh all` and installing through the Extension builder seems to have done the trick for me. 
<img width="682" alt="bildschirmfoto 2018-01-20 um 09 31 17" src="https://user-images.githubusercontent.com/35603251/35181576-d039d3bc-fdc4-11e7-999d-fd9536797627.png">
<img width="173" alt="bildschirmfoto 2018-01-20 um 09 21 33" src="https://user-images.githubusercontent.com/35603251/35181574-d00aabaa-fdc4-11e7-874c-7ecfdfd7f288.png">
<img width="1062" alt="bildschirmfoto 2018-01-20 um 09 22 05" src="https://user-images.githubusercontent.com/35603251/35181575-d0226678-fdc4-11e7-9f6f-a363bcfc5b9a.png">

**Comment by ghost** [comment] 2018-01-20 13:07
Can it be repackaged and added to releases?

**Comment by volcbs** [comment] 2018-01-20 15:57
@megadr01d You need to have the certificate, but then it won't be upgradeable to the next version (IIRC). So @el1t should be the one who does it.

**Comment by CasualDeveloper** [comment] 2018-01-20 16:16
Just wanted to say I'm having this issue too

**Comment by accolon** [comment] 2018-01-20 16:19
> ./tools/make-safari.sh all and installing through the Extension builder seems to have done the trick for me.

It even works if you extract the downloaded _uBlock0.safariextz_ (with _xar -xf_) and then install it through Extension Builder. It's a shame Safari doesn't provide any additional information what's wrong, or I'm looking in the wrong places.

Besides, the problem exists on both Safari versions right before and after the Meltdown/Spectre patches, while build 1.14.14 still works.

**Comment by maciejtarmas** [comment] 2018-01-20 22:12
Safari shows a pending update, but you can click the "Update" button to death and nothing happens.

Trying to install the new version manually results in the message like in the OP's bug report.

If only Firefox was as battery efficient as Safari, I'd switch in a sec.

Apple is going downhill with their QA lately. I'm seriously considering switching to Windows or Linux after years of being an Apple loyalist.

macOS 10.13.2
Safari 11.0.2 (13604.4.7.1.6)
<img width="882" alt="screen shot 2018-01-20 at 23 02 07" src="https://user-images.githubusercontent.com/3435387/35188525-d2e3d352-fe36-11e7-852f-9bdeda5cdd29.png">

**Comment by ghost** [comment] 2018-01-20 22:50
Hello,
I can confirm the update is showing as per maciejtarmas, looks like there is no action on the 'Update' button. However this is a issue with the signature. Safari is throwing a:

"CSSM Exception: -2147415734 CSSMERR_CSP_VERIFY_FAILED" in the console.app

[safari-ublock-update-log.txt](https://github.com/el1t/uBlock-Safari/files/1649363/safari-ublock-update-log.txt)

**Comment by volcbs** [comment] 2018-01-21 04:54
^ from this https://developer.apple.com/library/content/technotes/tn2318/_index.html
> If OCSP and CRL checking are temporarily turned off (in Keychain Access > Preferences > Certificates) and this resolves the Xcode build, reinstall Xcode (to restore its own signature) and also ensure there are no network connectivity issues on the Mac that is running Xcode.

**Comment by ghost** [comment] 2018-01-21 15:26
volcbs,

I do totally agree however the previous version 1.14.14 is being installed manually from the Release repo (https://github.com/el1t/uBlock-Safari-releases) and it is not showing the CSSM issue on install.
It is only 1.14.24 which seems to be not properly signed. Most likely 99% of the ublock origin users on safari do not even have Xcode installed or any other build tools.

**Comment by ghost** [comment] 2018-01-21 16:32
I contacted the dev by email on the 19th but no dice, I told him to look at this thread.

**Comment by PTDennis** [comment] 2018-01-21 18:58
Another one having the same issue. Hope the dev will release an update soon.

**Comment by vassudanagunta** [comment] 2018-01-21 19:23
FYI: Please everyone remember @el1t  does this port of uBlock Origin to Safari all on his own time, unpaid, and with little credit. And he's clearly busy. And no one else is stepping up to help maintain the port. On top of that some other user made his life more difficult (#69) and is the reason the Extension Gallery version is a problem. 

(feel free to vote up #71 to show some love)

**Comment by ghost** [comment] 2018-01-21 19:30
Excellent point @vassudanagunta .  We've been using 1.14.14 for months so we can wait for x.24 to get sorted at elt's convenience while still browsing with a good extension.

**Comment by nidstigator** [comment] 2018-01-21 20:33
Adding my voice to these appreciating all the work @el1t is doing!

The $99/year fee alone has been the reason most devs stayed away from porting uBlock to Safari.

**Comment by gingerbeardman** [comment] 2018-01-22 11:45
Also getting this.

Could it be released to the fact that it has also disappeared from the Safari Extensions Gallery?

**Comment by hmage** [comment] 2018-01-22 12:36
I'm getting this too.

No xcode, OSX 10.13.2, Safari 11.0.2 (13604.4.7.1.3).

uBlock 1.14.14 installs fine even after removing it and adding it back.

**Comment by agottardo** [comment] 2018-01-22 18:49
Getting this too on 11.0.2 (13604.4.7.1.6).

**Comment by gingerbeardman** [comment] 2018-01-22 19:21
Thanks for the info @vassudanagunta ! I had no idea the Safari extension gallery version was unauthorised.

**Comment by el1t** [comment] 2018-01-22 19:35
Sorry everyone, looks like the build script produced a bad extension. I've rebuilt it using Safari's extension builder, and it installs for me: [uBlock0.safariextz.zip](https://github.com/el1t/uBlock-Safari/files/1653309/uBlock0.safariextz.zip) (unzip first). I'll update the release if the issue is fixed.

The build might have failed due to a renewed certificate or the archive signing method becoming outdated—either way, I'll make sure to verify installation works next time.

**Comment by dart-h-vader** [comment] 2018-01-22 19:38
@maciejtarmas Though I acknowledge there is an issue with the extension, it is for the benefit of the users that the extension is failing to install. Granted, uBlock is a genuine piece of software but the signing is an essential step for keeping malicious extensions at bay.

**Comment by ghost** [comment] 2018-01-22 19:48
It auto-updated from 1.14.14 for me after your post.  Thanks for your work @el1t

**Comment by gingerbeardman** [comment] 2018-01-22 19:56
update from within safari worked for me just now. thanks

**Comment by el1t** [comment] 2018-01-22 20:16
Great! I'll close this issue since it looks fixed.

**Closed as completed by el1t** 2018-01-22 20:16 UTC

**Comment by timbuktu234** [comment] 2018-01-22 20:24
Extension working now, thank you!

**Comment by volcbs** [comment] 2018-01-23 09:26
Thank you!

**Comment by lsunsi** [comment] 2018-01-23 10:35
Thank you dude!

**Comment by maelcum** [comment] 2018-01-23 16:17
Thank you!

**Comment by ghost** [comment] 2018-01-27 16:20
@nidstigator 
> The $99/year fee alone has been the reason most devs stayed away from porting uBlock to Safari.

[Apple Developer Program Membership Fee Waivers Now Available](https://developer.apple.com/news/?id=01032018a) just as a note

and thanks el1t for your work !

**Comment by ruchernchong** [comment] 2018-01-28 04:36
@monouser7dig 

>We’re pleased to announce that Apple Developer Program membership is now available at no cost for **eligible organizations**. **Nonprofit organizations, accredited educational institutions, and government entities based in the United States**

**Comment by volcbs** [comment] 2018-01-28 10:26
>based in the United States

Could create pseudo-organization for ublock, but sadly gorhill is a Canadian.

**Comment by accolon** [comment] 2018-04-22 07:51
At least for me, the problem is back for the very recent v1.16.0. Anybody else?

EDIT for clarification: The downloaded .safariextz from the "Releases" section gives the "Safari can’t install this extension" described above.

**Comment by ruchernchong** [comment] 2018-04-22 07:53
@accolon if you are referring to the update not reflecting in the extensions, then yes. I am having the same problem as you right now.

**Comment by fostermarke** [comment] 2018-04-22 11:24
I have the same problem. Downloaded the extension and click to install produces a pop-up with:

Safari can’t install this extension
An error occurred while installing the extension “uBlock Origin”.

**Comment by maciboy** [comment] 2018-04-22 12:06
For me it worked seamlessly 😁 
Safari settings and the uBlock Origin menu itself reflect the update, saying 1.16.0
(Safari 11.0.3)

**Comment by fostermarke** [comment] 2018-04-22 15:09
Have just tried again but manually removed the previous version first.
Now success!

**Comment by marcothuemmler** [comment] 2018-04-22 17:33
Had the same problem. Removing the older version fixed it for me, too.

**Comment by ghost** [comment] 2018-05-07 20:34
Safari extension store is still serving the old 1.15.4 version. Are there any problems with the store authorisation.
